//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 11/11/2022 11:58:06 PM
namespace SuperMaket_project
{
    
    /// <summary>
    /// There are no comments for DBOModel.ssr in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="DBOModel", Name="ssr")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ssr : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ssr object.
        /// </summary>
        /// <param name="id_name">Initial value of id_name.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ssr Createssr(int id_name)
        {
            ssr ssr = new ssr();
            ssr.id_name = id_name;
            return ssr;
        }
        /// <summary>
        /// There are no comments for property id_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_name
        {
            get
            {
                return this._id_name;
            }
            set
            {
                this.Onid_nameChanging(value);
                this.ReportPropertyChanging("id_name");
                this._id_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_name");
                this.Onid_nameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_nameChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_nameChanged();
        /// <summary>
        /// There are no comments for property usert in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string usert
        {
            get
            {
                return this._usert;
            }
            set
            {
                this.OnusertChanging(value);
                this.ReportPropertyChanging("usert");
                this._usert = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("usert");
                this.OnusertChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _usert;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnusertChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnusertChanged();
    }
    /// <summary>
    /// There are no comments for DBOEntities in the schema.
    /// </summary>
    public partial class DBOEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DBOEntities object using the connection string found in the 'DBOEntities' section of the application configuration file.
        /// </summary>
        public DBOEntities() : 
                base("name=DBOEntities", "DBOEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DBOEntities object.
        /// </summary>
        public DBOEntities(string connectionString) : 
                base(connectionString, "DBOEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DBOEntities object.
        /// </summary>
        public DBOEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DBOEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ssrs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ssr> ssrs
        {
            get
            {
                if ((this._ssrs == null))
                {
                    this._ssrs = base.CreateQuery<ssr>("[ssrs]");
                }
                return this._ssrs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ssr> _ssrs;
        /// <summary>
        /// There are no comments for ssrs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTossrs(ssr ssr)
        {
            base.AddObject("ssrs", ssr);
        }
    }
}
